name: client_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  qr_flutter: ^4.0.0
  file_picker: '>=8.1.2'
  intl: 0.20.2
  shared_preferences: ^2.2.2 # For persistent login (Auto-Login)
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Use this specific path since your file is here
    - assets/ # Keep this as a general path for other assets
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true